paths:
  eeg_dir:   '/home/ubuntu/Github/codex/datasets/eeg'
  subject_dir:   'sub01'
  eeg_outside:   'preprocessed/outside_preprocessed.set'
  eeg_inside:    'preprocessed/inside_fMRIb_BCG_ICA.set'
  spike_timinmg: 'spike_timing.txt'
  #---
  ieeg_dir:   '/home/ubuntu/Github/codex/datasets/ieeg'

hyperparameters:
  sfreq: 250
  tr:    2.0

electrode_positions_10-10:
  Fp1:  [-0.3, 0.8]
  Fp2:  [0.3, 0.8]
  F3:   [-0.5, 0.6]
  F4:   [0.5, 0.6]
  C3:   [-0.5, 0.0]
  C4:   [0.5, 0.0]
  P3:   [-0.5, -0.6]
  P4:   [0.5, -0.6]
  O1:   [-0.3, -0.8]
  O2:   [0.3, -0.8]
  F7:   [-0.8, 0.5]
  F8:   [0.8, 0.5]
  T7:   [-1.0, 0.0]
  T8:   [1.0, 0.0]
  P7:   [-0.8, -0.5]
  P8:   [0.8, -0.5]
  Fz:   [0.0, 0.7]
  Cz:   [0.0, 0.0]
  Pz:   [0.0, -0.7]
  Oz:   [0.0, -0.9]
  FC1:  [-0.25, 0.3]
  FC2:  [0.25, 0.3]
  CP1:  [-0.25, -0.3]
  CP2:  [0.25, -0.3]
  FC5:  [-0.6, 0.4]
  FC6:  [0.6, 0.4]
  CP5:  [-0.6, -0.4]
  CP6:  [0.6, -0.4]
  TP9:  [-0.9, -0.2]
  TP10: [0.9, -0.2]
  POz:  [0.0, -0.8]
  F1:   [-0.2, 0.7]
  F2:   [0.2, 0.7]
  C1:   [-0.2, 0.0]
  C2:   [0.2, 0.0]
  P1:   [-0.2, -0.6]
  P2:   [0.2, -0.6]
  AF3:  [-0.35, 0.75]
  AF4:  [0.35, 0.75]
  FC3:  [-0.4, 0.4]
  FC4:  [0.4, 0.4]
  CP3:  [-0.4, -0.4]
  CP4:  [0.4, -0.4]
  PO3:  [-0.35, -0.7]
  PO4:  [0.35, -0.7]
  F5:   [-0.6, 0.6]
  F6:   [0.6, 0.6]
  C5:   [-0.6, 0.0]
  C6:   [0.6, 0.0]
  P5:   [-0.6, -0.6]
  P6:   [0.6, -0.6]
  AF7:  [-0.5, 0.75]
  AF8:  [0.5, 0.75]
  FT7:  [-0.8, 0.3]
  FT8:  [0.8, 0.3]
  TP7:  [-0.8, -0.3]
  TP8:  [0.8, -0.3]
  PO7:  [-0.5, -0.8]
  PO8:  [0.5, -0.8]
  FT9:  [-0.9, 0.1]
  FT10: [0.9, 0.1]
  Fpz:  [0.0, 0.85]
  CPz:  [0.0, -0.4]

electrode_positions_10-20:
  Fp1: [-0.3, 0.8]
  Fp2: [0.3, 0.8]
  F7:  [-0.8, 0.5]
  F8:  [0.8, 0.5]
  F3:  [-0.5, 0.5]
  F4:  [0.5, 0.5]
  T7:  [-1.0, 0.0]
  T8:  [1.0, 0.0]
  C3:  [-0.5, 0.0]
  C4:  [0.5, 0.0]
  P7:  [-0.8, -0.5]
  P8:  [0.8, -0.5]
  P3:  [-0.5, -0.5]
  P4:  [0.5, -0.5]
  O1:  [-0.3, -0.8]
  O2:  [0.3, -0.8]
  Fz:  [0.0, 0.6]
  Cz:  [0.0, 0.0]
  Pz:  [0.0, -0.6]

# Feel free to make your own list of electrodes and their position.
# You can copy the postions from the standard 10-10 system mentioned above.